### ISSUE TITLE
Help with source/dest setup

### ISSUE THREAD

**Issue by darren131** [assetify/assetify#15]
Hi there,

Firstly let me preface this with the following: I'm a total n00b so please excuse any obvious n00bness..

This is my project folder setup
http://cl.ly/image/1r07031i2v1j

This is what my assets.js file looks like:
```javascript
var assetify = require('assetify').instance(),
    pub = __dirname + '/src',
    bin = __dirname + '/public';

assetify.use(assetify.plugins.sass);
assetify.use(assetify.plugins.minifyCSS);
assetify.use(assetify.plugins.minifyJS);
assetify.use(assetify.plugins.bundle);

assetify.compile({
    source: pub,
    bin: bin,
    js: [
        {
            profile: "top",
            file: "../bower_components/jquery/dist/jquery.js",
            file: "../bower_components/fastclick/lib/fastclick.js",
            file: "scripts/top-modernizr.js"
        },
        {
            profile: "bottom",
            file: '../bower_components/foundation/js/foundation/foundation.js',
            file: '../bower_components/foundation/js/foundation/foundation.offcanvas.js',
            file: '../bower_components/foundation/js/foundation/foundation.reveal.js',
            file: '../bower_components/slick.js/slick/slick.js',
            file: 'scripts/app/main.js'
        }

    ]
}, function(err){
    if(err){
        throw err;
    }
});
```

when I run assets.js from the command line `node assets.js` I get the following error:
```
/Users/darren/Work/Liberate IT/liberate-it/node_modules/assetify/src/compiler.js:25
            throw new Error("opts.source must be defined as the folder where y
                  ^
Error: opts.source must be defined as the folder where your assets are
```

I'm at a total loss... :-/ Could you please point me in the right direction

**Comment by faceleg** [comment]
I don't know if this is related, but generally you should use `path` to render partial paths into absolutes, e.g.

```JS
var path = require('path');

var filePath = path.join(__dirname, '../some_directory/', 'some_file.js');

console.log(filePath);
```

**Comment by bevacqua** [comment]
Also this object makes no sense:

```
        {
            profile: "bottom",
            file: '../bower_components/foundation/js/foundation/foundation.js',
            file: '../bower_components/foundation/js/foundation/foundation.offcanvas.js',
            file: '../bower_components/foundation/js/foundation/foundation.reveal.js',
            file: '../bower_components/slick.js/slick/slick.js',
            file: 'scripts/app/main.js'
        }
```

**Comment by faceleg** [comment]
Wow can't believe I didn't spot that.

@darren131 JavaScript objects are hashes - you are only allowed one value per key.

**Comment by darren131** [comment]
Okay – thanks for the help with this... I'm still somewhat lost, and this refers back to my lack of knowledge... Let me explain what I'm wanting to do:

I'd like to compile multiple js files

`top.js` contains:
             "../bower_components/jquery/dist/jquery.js",
             "../bower_components/fastclick/lib/fastclick.js",
             "scripts/top-modernizr.js"

and `bottom.js` contains:
             '../bower_components/foundation/js/foundation/foundation.js',
             '../bower_components/foundation/js/foundation/foundation.offcanvas.js',
             '../bower_components/foundation/js/foundation/foundation.reveal.js',
             '../bower_components/slick.js/slick/slick.js',
             'scripts/app/main.js'


Is this even possible?
